### ISSUE TITLE
Server side

### ISSUE THREAD

**Issue by omidb** [mathieuleclaire/scalaWUI#1]
Hi,

thanks for this sample project. I couldn't understand what exactly is transferring between client and server. Would you please make it clear for me?

And one other question is, what is the best way, (if any exist ), to use your d3 porting with scala-react-js?

Thanks

**Comment by mathieuleclaire** [comment]
Hi,
in this example, a few things ! I just call the server to get a UUID, just to show how the server calls work: [See here](https://github.com/mathieuleclaire/scalaTraJSTagsWireRx/blob/master/client/src/main/scala/fr/iscpif/client/FlowChart.scala#L170.)

I don't know scala-react, I choosed scala.rx, which really works very well (the circle moves are done with it for instance in the example). 

You can also get some inspirations from the openmole project that I am developping:  (https://github.com/openmole/openmole/tree/master/openmole/gui)

By the way, I should upgrade all the dependency versions.

**Comment by omidb** [comment]
I wanted to use your project to send a graph from server to client, changing it in client and send it back to server. one problem I have is layouting the graph in client side, I found [dagre-d3](https://github.com/cpettitt/dagre-d3) usefull for layouting graph but I have no idea how to use it with your exisiting graph. I'm kind of lost now!

**Comment by mathieuleclaire** [comment]
Getting graph settings from client is easy: you just need to construct a representation of your graph as case classes (autowire requires case classes).

Concerning the layouting, what do you want to deals with ? In this example, you can move nodes, add/destroy nodes, add/destroy edges. Do you need something more ?

**Comment by omidb** [comment]
so to layout one of your client side graphs for example to something like [this](http://cpettitt.github.io/project/dagre-d3/latest/demo/tcp-state-diagram.html), I have to write my own algorithm to move every nodes positions. I don't know how to integrate something like dagre-d3 with this to layout the graph.

**Comment by mathieuleclaire** [comment]
The move position is still working. You could extend what I already did. Did you succeed in launching the application ?

**Comment by omidb** [comment]
Yes, it runs fine. but the initial layout is by hand which would be nice to have a layout algorithm like dagre to do that.

**Comment by mathieuleclaire** [comment]
You can use one of the D3 layout algorithm. My application depends on scaladget, which provides some mapping for js libs and among them: [d3](https://github.com/mathieuleclaire/scaladget/blob/master/scaladget/src/main/scala/fr/iscpif/scaladget/mapping/d3mapping.scala). You can use it to hack my code and generate your layout.

**Comment by mathieuleclaire** [comment]
Hi, I upgraded the project with last versions of scala-js and satellite projects. You just need one more step now (copy by hand your generated js). I'll find a cleaner way to do so.

**Comment by mathieuleclaire** [comment]
Hey,
the project has been updated, just one command "go" is enough to build the js files and copy all the stuff at the right place before launching the server !
