### ISSUE TITLE
[UNRESOLVED DEPENDENCIES] it use sbteclipse plugin

### ISSUE THREAD

**Issue by matsushi48** [mathieuleclaire/scalaWUI#2]
Thunk you useful example project!
I can build & run scalaWUI project reading readme.
But I can't convert to eclipse project by sbteclipse plugin,
because client project unresolved the dependencies of scaladget 0.5.0-SNAPSHOT.

I add code to ScalaWUIBuild.scala from this.

32   resolvers ++= Resolvers,  //before
32   resolvers in ThisBuild ++= Resolvers, //after

I can resolve snapshot dependencies.

Please add this code to you project for eclipse users.

**Comment by mathieuleclaire** [comment]
Thanks, it is now fixed
