### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by annyanich** [mathieuleclaire/scalaWUI#8]
Hi Mathieu,

I was wanting to base a project of mine off of this skeleton, but there doesn't appear to be any specific license specified for this repo.  Could you please add one?  

All the best,
Ann

**Comment by annyanich** [comment]
I looked further and I found a comment in FlowChart.scala saying that it's licensed under the GPL v3.  Does this license apply to the rest of the repo as well?

**Comment by mathieuleclaire** [comment]
Yes it is, I added this on the whole project. Thanks !
